# Generated by Django 3.1.4 on 2021-05-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happy_clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profession', models.CharField(max_length=100, verbose_name='profession')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('body', models.CharField(max_length=255, verbose_name='massage')),
            ],
        ),
    ]
